#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
sources =  Glob("src/*.cpp")
sources += Glob("src/classes/*.cpp")
sources += Glob("src/classes/game/*.cpp")
sources += Glob("src/core/*.cpp")
sources += Glob("src/classes/ui/*.cpp")
sources += Glob("src/classes/ui/inventory/*.cpp")
sources += Glob("src/classes/ui/effects/*.cpp")
sources += Glob("src/classes/inventory/*.cpp")
sources += Glob("src/classes/interactable/*.cpp")
sources += Glob("src/classes/pawns/*.cpp")
sources += Glob("src/classes/level/*.cpp")

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "../bin/nightmare.{}.{}.framework/nightmare.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "../bin/nightmare{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )
    # env["PDB"] = env["target"] + ".pdb"

Default(library)
